version: '2'
services:
    gestionstock-app:
        image: gestionstock
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gestionstock-mysql:3306/gestionstock?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gestionstock-mysql:
        extends:
            file: mysql.yml
            service: gestionstock-mysql
